import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLORS } from '../../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
    full: { flex: 1, backgroundColor: COLORS.warmWhite },
    dashHdr: { paddingTop: Platform.OS === 'ios' ? 0 : 20, height: Platform.OS === 'ios' ? 75 : 95, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, backgroundColor: COLORS.white, borderBottomWidth: 1, borderBottomColor: COLORS.lightGray + '20' },
    subHdr: { height: 75, backgroundColor: COLORS.forest, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
    tabPillRowNew: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 30,
        padding: 5,
        width: '90%',
        alignSelf: 'center',
    },
    tabPillNew: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
    },
    tabPillActNew: {
        backgroundColor: COLORS.white,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 4,
    },
    tabPillTextNew: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.7)' },
    tabPillTextActNew: { fontSize: 13, fontWeight: '800', color: COLORS.forest },
    healthSumBdg: { alignItems: 'flex-end' },
    healthSumVal: { fontSize: 16, fontWeight: '900', color: COLORS.lime },
    healthSumLbl: { fontSize: 8, color: COLORS.white, fontWeight: '700', textTransform: 'uppercase' },
    iconCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: COLORS.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.lightGray + '40' },
    scrollContent: { padding: 20, paddingBottom: 100 },
    helloText: { fontSize: 13, color: COLORS.warmGray, fontWeight: '600', marginTop: 10 },
    farmerName: { fontSize: 24, fontWeight: '900', color: COLORS.deepOlive, marginTop: 2 },
    statsRow: { flexDirection: 'row', gap: 8, marginVertical: 10 },
    statCard: { flex: 1, alignItems: 'center', paddingVertical: 12 },
    statVal: { fontSize: 20, fontWeight: '900' },
    statLabel: { fontSize: 9, color: COLORS.warmGray, textTransform: 'uppercase', marginTop: 2 },
    weatherCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 18, backgroundColor: COLORS.cream, marginBottom: 20 },
    weatherStat: { alignItems: 'flex-end', gap: 4 },
    wSub: { fontSize: 11, fontWeight: '700', color: COLORS.earth },
    fieldCard: { padding: 0, overflow: 'hidden', marginBottom: 14 },
    fieldMapPlaceholder: { height: 120, backgroundColor: COLORS.forest, position: 'relative' },
    fieldBdg: { position: 'absolute', top: 12, right: 12, backgroundColor: 'rgba(0,0,0,0.4)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 20 },
    fieldBdgText: { color: COLORS.lime, fontSize: 10, fontWeight: '800' },
    fieldInfo: { padding: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    fieldTitle: { fontSize: 15, fontWeight: '800', color: COLORS.darkEarth },
    fieldSub: { fontSize: 12, color: COLORS.warmGray },
    tabBar: { height: 70, flexDirection: 'row', backgroundColor: COLORS.white, borderTopWidth: 1, borderTopColor: COLORS.lightGray + '30', paddingBottom: 10 },
    tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', position: 'relative' },
    tabLabel: { fontSize: 9, fontWeight: '700', color: COLORS.warmGray, marginTop: 2 },
    tabIndicator: { position: 'absolute', bottom: 5, width: 16, height: 3, borderRadius: 2, backgroundColor: COLORS.forest },
    progressRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingBottom: 12 },
    progressTrack: { flex: 1, height: 4, backgroundColor: COLORS.lightGray + '40', borderRadius: 2, overflow: 'hidden' },
    progressFill: { height: '100%', backgroundColor: COLORS.forest, borderRadius: 2 },
    addNewCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#00897B', alignItems: 'center', justifyContent: 'center', elevation: 4, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
    detailCover: { height: 220, position: 'relative' },
    backBtnDet: { position: 'absolute', top: 20, left: 20, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },
    detailOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 20, backgroundColor: 'rgba(0,0,0,0.4)' },
    tlRow: { flexDirection: 'row', gap: 16, position: 'relative', paddingBottom: 20 },
    tlDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: COLORS.lightGray, zIndex: 1, marginTop: 4 },
    tlDotActive: { backgroundColor: COLORS.forest, borderWidth: 3, borderColor: COLORS.paleGreen },
    tlLine: { position: 'absolute', left: 5, top: 16, bottom: -4, width: 2, backgroundColor: COLORS.lightGray + '60' },
    tlText: { fontSize: 14, fontWeight: '700', color: COLORS.warmGray },
    nowBdg: { marginLeft: 8, fontSize: 10, fontWeight: '800', color: COLORS.forest, backgroundColor: COLORS.paleGreen, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
    mapControls: { position: 'absolute', bottom: 30, left: 20, right: 20 },
    stressZone: { position: 'absolute', borderRadius: 10, borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#fff' },

    // -- New Premium Dashboard Styles --
    weatherCardNew: {
        padding: 20,
        borderRadius: 24,
        marginBottom: 24,
        borderWidth: 1,
        elevation: 0,
        shadowColor: 'transparent',
    },
    weatherStatItem: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 16,
        gap: 8,
    },
    weatherStatLabel: {
        fontSize: 14,
        fontWeight: '800',
    },
    weatherStatType: {
        fontSize: 9,
        fontWeight: '700',
        color: COLORS.warmGray,
        textTransform: 'uppercase',
    },
    fieldCardContainer: {
        marginBottom: 20,
        position: 'relative',
    },
    selBadge: {
        position: 'absolute',
        top: 15,
        right: 15,
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 50,
        elevation: 6,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        borderWidth: 2,
        borderColor: 'white',
        backgroundColor: 'rgba(255,255,255,0.4)',
    },
});
